basePath: /api
definitions:
  domain.CreatePaymentRequest:
    properties:
      amount:
        type: number
      method:
        enum:
        - credit_card
        - paypal
        - bank_transfer
        type: string
      order_id:
        type: string
      user_id:
        type: string
    required:
    - amount
    - method
    - order_id
    - user_id
    type: object
  domain.Payment:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      id:
        type: string
      orderId:
        type: string
      status:
        description: e.g., "pending", "completed", "failed"
        type: string
      updatedAt:
        type: string
      userId:
        type: string
    type: object
host: localhost:8084
info:
  contact: {}
  description: This is the Payment microservice.
  title: Payment Microservice API
  version: "1.0"
paths:
  /payments:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Payment'
            type: array
      summary: List all payments
      tags:
      - payments
    post:
      consumes:
      - application/json
      parameters:
      - description: Payment Data
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/domain.CreatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Create a new payment
      tags:
      - payments
  /payments/{id}:
    delete:
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Error deleting
          schema:
            type: string
      summary: Delete a payment
      tags:
      - payments
    get:
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
        "404":
          description: Payment not found
          schema:
            type: string
      summary: Get payment by ID
      tags:
      - payments
    put:
      consumes:
      - application/json
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      - description: New Status
        in: body
        name: status
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
      summary: Update payment status
      tags:
      - payments
swagger: "2.0"
